-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
        exclude: ^vendor/
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: detect-private-key
        exclude: ^(bootstrap|Font-Awesome|scifiweb/static/(fonts|scss/(bootstrap|font-awesome)))$
    -   id: double-quote-string-fixer
        language_version: python3
        exclude: ^manage.py$
    -   id: end-of-file-fixer
    -   id: flake8
        language_version: python3
        exclude: ^(vendor/|manage.py$)
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.2
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade.git
    sha: v1.1.0
    hooks:
    -   id: pyupgrade
        language_version: python3
        args: ['--py3-plus']
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.0.1
    hooks:
    -   id: remove-tabs
        exclude: ^(Makefile|bootstrap|Font-Awesome|scifiweb/static/(fonts|scss/(bootstrap|font-awesome)))$
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-scss-lint.git
    sha: v0.53.0
    hooks:
    -   id: scss-lint
        exclude: ^(bootstrap|Font-Awesome|scifiweb/static/scss/bootstrap/(bootstrap|font-awesome))$
