linters:
    LeadingZero:
        style: include_zero

    NestingDepth:
        enabled: false

    SelectorDepth:
        enabled: false

    ColorVariable:
        enabled: false

    PlaceholderInExtend:
        enabled: false

    # why does anyone think this is a good idea?
    PropertySortOrder:
        enabled: false

    Indentation:
        enabled: true
        width: 4

    ColorKeyword:
        enabled: false

    # don't want to force using `//` comments everywhere
    Comment:
        enabled: false

    SingleLinePerSelector:
        enabled: false

    HexLength:
        enabled: false

    HexNotation:
        enabled: false

    ImportantRule:
        enabled: false

    SelectorFormat:
        enabled: false
